services:
  tictactoe:
    build: .
    container_name: tictactoe
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    external:
      name: network-services_network_services
